Issue 161
snowdrop-bot/snowdrop-bot pull request #163
Opened 2021-04-28 08:20 UTC by cmoulliard

- Refactor the project to use github actions as CI
- Add an action to build & push container images on quay.io/snowdrop/snowdrop-bot
- Upgrade the BOM to be able to use fast-jar
- Simplify the instructions to create secrets.
- Remove the non needed section to build the image

2021-04-28 08:26 UTC, cmoulliard commented
Can you disable this project on circleci as now we will use github actions @jacobdotcosta ?

2021-04-28 09:46 UTC, aureamunoz requested changes
Other than this minor typo fix, LGTM!

2021-04-28 09:46 UTC, aureamunoz commented on README.md
> +The parameters are passes using the argument `-D`
passes -> passed

2021-04-28 13:42 UTC, aureamunoz approved these changes
LGTM

2021-04-28 14:08 UTC, jacobdotcosta approved these changes
LGTM

2021-04-28 14:29 UTC, merged

2021-04-29 14:37 UTC, aureamunoz commented on README.md
> +1. Verify that PV volumes exist to bound the PVC of the bot with a volume of 2Gi. See [appendix](#appendix) to create a PV if needed.
I would help: `kubectl get pvc`

2021-04-29 14:37 UTC, aureamunoz commented on README.md
>  export GITHUB_TOKEN=`pass show snowdrop/github.com/snowdrop-bot/token`
The path is wrong. The correct is `github.com/snowdrop-bot/token`, do the command should be: export GITHUB_TOKEN=`pass show github.com/snowdrop-bot/token`

2021-04-29 14:37 UTC, aureamunoz commented on README.md
> +export jira_password=`pass show snowdrop/rh/jira/snowdrop-jirabot`
The path is wrong. The good one is: `rh/jira/snowdrop-jirabot`